snapcraft-version: 8.8.1
snapcraft-started-at: '2025-05-07T07:45:09.696752Z'
snapcraft-os-release-id: ubuntu
snapcraft-os-release-version-id: '24.04'
name: udisks2
version: 2.10.1-3
summary: Storage devices management service
description: |
  Udisks2 provides a dbus service that can query and manager
  storages devices as well as a command-line tool.
base: core24
grade: stable
confinement: strict
apps:
  udisksd:
    command: usr/libexec/udisks2/udisksd
    daemon: dbus
    slots:
    - udisks2
    plugs:
    - hardware-observe
    - mount-observe
    - polkit
    - block-devices
    daemon-scope: system
    activates-on:
    - udisks2-dbus
  udisksctl:
    command: usr/bin/udisksctl
    plugs:
    - udisks2-client
parts:
  udisks2-copyright:
    plugin: nil
    stage-packages:
    - adduser=3.137ubuntu1
    - dirmngr=2.4.4-2ubuntu17.2
    - gnupg-utils=2.4.4-2ubuntu17.2
    - gnupg=2.4.4-2ubuntu17.2
    - gpg-agent=2.4.4-2ubuntu17.2
    - gpg=2.4.4-2ubuntu17.2
    - gpgconf=2.4.4-2ubuntu17.2
    - gpgsm=2.4.4-2ubuntu17.2
    - keyboxd=2.4.4-2ubuntu17.2
    - libatasmart4=0.19-5build3
    - libblockdev-crypto3=3.1.1-1
    - libblockdev-fs3=3.1.1-1
    - libblockdev-loop3=3.1.1-1
    - libblockdev-mdraid3=3.1.1-1
    - libblockdev-nvme3=3.1.1-1
    - libblockdev-part3=3.1.1-1
    - libblockdev-swap3=3.1.1-1
    - libblockdev-utils3=3.1.1-1
    - libblockdev3=3.1.1-1
    - libbytesize-common=2.10-1ubuntu2
    - libbytesize1=2.10-1ubuntu2
    - libgpgme11t64=1.18.0-4.1ubuntu4
    - libgudev-1.0-0=1:238-5ubuntu1
    - libksba8=1.6.6-1build1
    - libldap2=2.6.7+dfsg-1~exp1ubuntu8.2
    - libmpfr6=4.2.1-1build1.1
    - libnspr4=2:4.35-1.1build1
    - libnss3=2:3.98-1build1
    - libnvme1t64=1.8-3ubuntu1
    - libparted2t64=3.6-4build1
    - libsasl2-2=2.1.28+dfsg1-5ubuntu3.1
    - libsasl2-modules-db=2.1.28+dfsg1-5ubuntu3.1
    - libudisks2-0=2.10.1-6ubuntu1
    - libvolume-key1=0.3.12-7build2
    - parted=3.6-4build1
    - pinentry-curses=1.2.1-3ubuntu5
    - udisks2=2.10.1-6ubuntu1
    override-build: |
      cp -r "${CRAFT_PART_INSTALL}/usr/share/doc" doc
      rm -rf "${CRAFT_PART_INSTALL}"
      install -Dm644 -t "${CRAFT_PART_INSTALL}/usr/share/doc/udisks2" doc/udisks2/copyright doc/udisks2/changelog.*
    stage: []
    prime: []
    build-packages: []
  udisks2:
    build-environment:
    - XDG_DATA_DIRS: /usr/local/share/:/usr/share/:/build/udisks2/stage/usr/share/
    build-packages:
    - meson
    - pkg-config
    - libglib2.0-dev
    - libgudev-1.0-dev
    - libblockdev-dev
    - libatasmart-dev
    - libblockdev-part-dev
    - libblockdev-loop-dev
    - libblockdev-swap-dev
    - libblockdev-mdraid-dev
    - libblockdev-fs-dev
    - libblockdev-nvme-dev
    - libblockdev-crypto-dev
    - libpolkit-agent-1-dev
    - libpolkit-gobject-1-dev
    - gettext
    - xsltproc
    - docbook-xsl
    - polkitd
    stage-packages:
    - adduser=3.137ubuntu1
    - dirmngr=2.4.4-2ubuntu17.2
    - gnupg-utils=2.4.4-2ubuntu17.2
    - gnupg=2.4.4-2ubuntu17.2
    - gpg-agent=2.4.4-2ubuntu17.2
    - gpg=2.4.4-2ubuntu17.2
    - gpgconf=2.4.4-2ubuntu17.2
    - gpgsm=2.4.4-2ubuntu17.2
    - keyboxd=2.4.4-2ubuntu17.2
    - libatasmart4=0.19-5build3
    - libblockdev-crypto3=3.1.1-1
    - libblockdev-fs3=3.1.1-1
    - libblockdev-loop3=3.1.1-1
    - libblockdev-mdraid3=3.1.1-1
    - libblockdev-nvme3=3.1.1-1
    - libblockdev-part3=3.1.1-1
    - libblockdev-swap3=3.1.1-1
    - libblockdev-utils3=3.1.1-1
    - libblockdev3=3.1.1-1
    - libbytesize-common=2.10-1ubuntu2
    - libbytesize1=2.10-1ubuntu2
    - libgpgme11t64=1.18.0-4.1ubuntu4
    - libgudev-1.0-0=1:238-5ubuntu1
    - libksba8=1.6.6-1build1
    - libldap2=2.6.7+dfsg-1~exp1ubuntu8.2
    - libmpfr6=4.2.1-1build1.1
    - libnspr4=2:4.35-1.1build1
    - libnss3=2:3.98-1build1
    - libnvme1t64=1.8-3ubuntu1
    - libsasl2-2=2.1.28+dfsg1-5ubuntu3.1
    - libsasl2-modules-db=2.1.28+dfsg1-5ubuntu3.1
    - libvolume-key1=0.3.12-7build2
    - pinentry-curses=1.2.1-3ubuntu5
    plugin: autotools
    autotools-configure-parameters:
    - --prefix=/usr
    - --enable-fhs-media
    source-type: git
    source-branch: applied/ubuntu/noble-updates
    source: https://git.launchpad.net/ubuntu/+source/udisks2
    override-pull: |
      craftctl default
      patch -p1 <"/build/udisks2/proc-mountinfo.patch"
    stage: []
    prime: []
  policy:
    plugin: nil
    after:
    - udisks2
    override-build: |
      install -Dm644 \
        "/build/udisks2/stage/usr/share/polkit-1/actions/org.freedesktop.UDisks2.policy" \
        "${CRAFT_PART_INSTALL}/meta/polkit/polkit.org.freedesktop.UDisks2.policy"
    stage-packages: []
    stage: []
    prime: []
    build-packages: []
architectures:
- arm64
image-info:
  build_url: https://launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+snap/udisks2-snap-24/+build/2797297
build-packages: []
build-snaps: []
primed-stage-packages:
- adduser=3.137ubuntu1
- dirmngr=2.4.4-2ubuntu17.2
- gnupg-utils=2.4.4-2ubuntu17.2
- gnupg=2.4.4-2ubuntu17.2
- gpg-agent=2.4.4-2ubuntu17.2
- gpg=2.4.4-2ubuntu17.2
- gpgconf=2.4.4-2ubuntu17.2
- gpgsm=2.4.4-2ubuntu17.2
- keyboxd=2.4.4-2ubuntu17.2
- libatasmart4=0.19-5build3
- libblockdev-crypto3=3.1.1-1
- libblockdev-fs3=3.1.1-1
- libblockdev-loop3=3.1.1-1
- libblockdev-mdraid3=3.1.1-1
- libblockdev-nvme3=3.1.1-1
- libblockdev-part3=3.1.1-1
- libblockdev-swap3=3.1.1-1
- libblockdev-utils3=3.1.1-1
- libblockdev3=3.1.1-1
- libbytesize-common=2.10-1ubuntu2
- libbytesize1=2.10-1ubuntu2
- libgpgme11t64=1.18.0-4.1ubuntu4
- libgudev-1.0-0=1:238-5ubuntu1
- libksba8=1.6.6-1build1
- libldap2=2.6.7+dfsg-1~exp1ubuntu8.2
- libmpfr6=4.2.1-1build1.1
- libnspr4=2:4.35-1.1build1
- libnss3=2:3.98-1build1
- libnvme1t64=1.8-3ubuntu1
- libsasl2-2=2.1.28+dfsg1-5ubuntu3.1
- libsasl2-modules-db=2.1.28+dfsg1-5ubuntu3.1
- libvolume-key1=0.3.12-7build2
- pinentry-curses=1.2.1-3ubuntu5
