snapcraft-version: 8.14.5.post106
snapcraft-started-at: '2026-04-27T20:09:01.511797Z'
snapcraft-os-release-id: ubuntu
snapcraft-os-release-version-id: '26.04'
name: udisks2
version: 2.10.91-1
summary: Storage devices management service
description: |
  Udisks2 provides a dbus service that can query and manager
  storages devices as well as a command-line tool.
base: core26
grade: stable
confinement: strict
apps:
  udisksd:
    command: usr/libexec/udisks2/udisksd
    daemon: dbus
    slots:
    - udisks2
    plugs:
    - hardware-observe
    - mount-observe
    - polkit
    - block-devices
    daemon-scope: system
    activates-on:
    - udisks2-dbus
  udisksctl:
    command: usr/bin/udisksctl
    plugs:
    - udisks2-client
parts:
  udisks2-copyright:
    plugin: nil
    stage-packages:
    - adduser=3.153ubuntu1
    - dirmngr=2.4.8-4ubuntu3
    - gnupg=2.4.8-4ubuntu3
    - gpg-agent=2.4.8-4ubuntu3
    - gpg=2.4.8-4ubuntu3
    - gpgconf=2.4.8-4ubuntu3
    - gpgsm=2.4.8-4ubuntu3
    - libatasmart4=0.19-6
    - libblockdev-crypto3=3.4.0-1
    - libblockdev-fs3=3.4.0-1
    - libblockdev-loop3=3.4.0-1
    - libblockdev-mdraid3=3.4.0-1
    - libblockdev-nvme3=3.4.0-1
    - libblockdev-part3=3.4.0-1
    - libblockdev-smart3=3.4.0-1
    - libblockdev-swap3=3.4.0-1
    - libblockdev-utils3=3.4.0-1
    - libblockdev3=3.4.0-1
    - libbytesize-common=2.12-1
    - libbytesize1=2.12-1
    - libgpgme45=2.0.1-2build1
    - libgudev-1.0-0=1:238-7build1
    - libksba8=1.6.7-2build1
    - libldap-common=2.6.10+dfsg-1ubuntu5
    - libldap2=2.6.10+dfsg-1ubuntu5
    - libmpfr6=4.2.2-3
    - libnspr4=2:4.38.2-1ubuntu1
    - libnss3=2:3.120-1ubuntu2
    - libnvme1t64=1.16.1-4
    - libparted2t64=3.6-6
    - libsasl2-2=2.1.28+dfsg1-9ubuntu3
    - libsasl2-modules-db=2.1.28+dfsg1-9ubuntu3
    - libudisks2-0=2.10.91-1ubuntu2
    - libvolume-key1=0.3.12-10build2
    - parted=3.6-6
    - pinentry-curses=1.3.2-3ubuntu1
    - udisks2=2.10.91-1ubuntu2
    override-build: |
      cp -r "${CRAFT_PART_INSTALL}/usr/share/doc" doc
      rm -rf "${CRAFT_PART_INSTALL}"
      install -Dm644 -t "${CRAFT_PART_INSTALL}/usr/share/doc/udisks2" doc/udisks2/copyright doc/udisks2/changelog.*
    stage: []
    prime: []
    build-packages: []
  udisks2:
    build-environment:
    - XDG_DATA_DIRS: /usr/local/share/:/usr/share/:/build/udisks2/stage/usr/share/
    build-packages:
    - meson
    - pkg-config
    - libglib2.0-dev
    - libgudev-1.0-dev
    - libblockdev-dev
    - libatasmart-dev
    - libblockdev-part-dev
    - libblockdev-loop-dev
    - libblockdev-swap-dev
    - libblockdev-mdraid-dev
    - libblockdev-fs-dev
    - libblockdev-nvme-dev
    - libblockdev-crypto-dev
    - libpolkit-agent-1-dev
    - libpolkit-gobject-1-dev
    - libblockdev-smart-dev
    - gettext
    - xsltproc
    - docbook-xsl
    - polkitd
    stage-packages:
    - adduser=3.153ubuntu1
    - dirmngr=2.4.8-4ubuntu3
    - gnupg=2.4.8-4ubuntu3
    - gpg-agent=2.4.8-4ubuntu3
    - gpg=2.4.8-4ubuntu3
    - gpgconf=2.4.8-4ubuntu3
    - gpgsm=2.4.8-4ubuntu3
    - libatasmart4=0.19-6
    - libblockdev-crypto3=3.4.0-1
    - libblockdev-fs3=3.4.0-1
    - libblockdev-loop3=3.4.0-1
    - libblockdev-mdraid3=3.4.0-1
    - libblockdev-nvme3=3.4.0-1
    - libblockdev-part3=3.4.0-1
    - libblockdev-smart3=3.4.0-1
    - libblockdev-swap3=3.4.0-1
    - libblockdev-utils3=3.4.0-1
    - libblockdev3=3.4.0-1
    - libbytesize-common=2.12-1
    - libbytesize1=2.12-1
    - libgpgme45=2.0.1-2build1
    - libgudev-1.0-0=1:238-7build1
    - libksba8=1.6.7-2build1
    - libldap-common=2.6.10+dfsg-1ubuntu5
    - libldap2=2.6.10+dfsg-1ubuntu5
    - libmpfr6=4.2.2-3
    - libnspr4=2:4.38.2-1ubuntu1
    - libnss3=2:3.120-1ubuntu2
    - libnvme1t64=1.16.1-4
    - libsasl2-2=2.1.28+dfsg1-9ubuntu3
    - libsasl2-modules-db=2.1.28+dfsg1-9ubuntu3
    - libvolume-key1=0.3.12-10build2
    - pinentry-curses=1.3.2-3ubuntu1
    prime:
    - -usr/lib/*/libnssckbi.so*
    - -usr/lib/*/libnssdbm3*
    plugin: autotools
    autotools-configure-parameters:
    - --prefix=/usr
    - --enable-fhs-media
    - --with-udevdir=/usr/lib/udev
    source-type: git
    source-branch: applied/ubuntu/resolute
    source: https://git.launchpad.net/ubuntu/+source/udisks2
    override-pull: |
      craftctl default
      patch -p1 <"/build/udisks2/proc-mountinfo.patch"
    stage: []
  policy:
    plugin: nil
    after:
    - udisks2
    override-build: |
      install -Dm644 \
        "/build/udisks2/stage/usr/share/polkit-1/actions/org.freedesktop.UDisks2.policy" \
        "${CRAFT_PART_INSTALL}/meta/polkit/polkit.org.freedesktop.UDisks2.policy"
    stage-packages: []
    stage: []
    prime: []
    build-packages: []
architectures:
- armhf
image-info:
  build_url: https://launchpad.net/~snappy-hwe-team/+snap/udisks2-snap-26/+build/3134572
build-packages: []
build-snaps: []
primed-stage-packages:
- adduser=3.153ubuntu1
- dirmngr=2.4.8-4ubuntu3
- gnupg=2.4.8-4ubuntu3
- gpg-agent=2.4.8-4ubuntu3
- gpg=2.4.8-4ubuntu3
- gpgconf=2.4.8-4ubuntu3
- gpgsm=2.4.8-4ubuntu3
- libatasmart4=0.19-6
- libblockdev-crypto3=3.4.0-1
- libblockdev-fs3=3.4.0-1
- libblockdev-loop3=3.4.0-1
- libblockdev-mdraid3=3.4.0-1
- libblockdev-nvme3=3.4.0-1
- libblockdev-part3=3.4.0-1
- libblockdev-smart3=3.4.0-1
- libblockdev-swap3=3.4.0-1
- libblockdev-utils3=3.4.0-1
- libblockdev3=3.4.0-1
- libbytesize-common=2.12-1
- libbytesize1=2.12-1
- libgpgme45=2.0.1-2build1
- libgudev-1.0-0=1:238-7build1
- libksba8=1.6.7-2build1
- libldap-common=2.6.10+dfsg-1ubuntu5
- libldap2=2.6.10+dfsg-1ubuntu5
- libmpfr6=4.2.2-3
- libnspr4=2:4.38.2-1ubuntu1
- libnss3=2:3.120-1ubuntu2
- libnvme1t64=1.16.1-4
- libsasl2-2=2.1.28+dfsg1-9ubuntu3
- libsasl2-modules-db=2.1.28+dfsg1-9ubuntu3
- libvolume-key1=0.3.12-10build2
- pinentry-curses=1.3.2-3ubuntu1
